version: 2.1
orbs:
  auto_ci: nowsecure/ci-auto-orb@1.2.1
jobs:
  build:
    docker:
    - image: openjdk:8
    steps:
    - attach_workspace:
        at: /tmp/myworkspace
    - checkout
    - run: cp azureauthenticator.apk /tmp/myworkspace/test.apk
    - auto_ci/mobile_security_test:
        auto_file: /tmp/myworkspace/test.apk
        auto_wait: "30"
        auto_score: "50"
        auto_show_status_messages: "true"
    - context:
        - work
