title: "[bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to help improve our software!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the errenous behaviour that you encountered.
      value: "Something chrashed!"
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: What should've happened?
      description: Describe the expected behaviour.
      value: "Should not have crashed!"
    validations:
      required: true
  - type: dropdown
    id: cli-tool
    attributes:
      label: CLI Tool
      description: Which CLI tool are you using?
      options:
        - Platform
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Please copy and paste all relevant log output. Logs must be complete in order for us to help you.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Contributing Guidelines](./CONTRIBUTING.md).
      options:
        - label: I agree to follow the Contributing Guidelines.
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: F.A.Q.
      description: By submitting this issue, you certify that you have read the F.A.Q. and not found a sufficient answer.
      options:
        - label: I have read the F.A.Q. and did not find a suffient answer.
          required: true


